

CREATE TABLE IF NOT EXISTS `flight_log_item` (
  `logfile_id` INTEGER NOT NULL,
  `timestamp` VARCHAR(40),
  `aircraft_lon` DOUBLE(12),
  `aircraft_lat` DOUBLE(12),
  `aircraft_altitude` DOUBLE(12),
  `aircraft_speed` DOUBLE(12),
  `aircraft_heading` DOUBLE(12),
  `aircraft_vel_x` DOUBLE(12),
  `aircraft_vel_y` DOUBLE(12),
  `aircraft_vel_z` DOUBLE(12),
  `aircraft_pitch` DOUBLE(12),
  `aircraft_roll` DOUBLE(12),
  `aircraft_yaw` DOUBLE(12),
  `aircraft_satellites` INT(12),
  `aircraft_motors_on` BOOL,
  `aircraft_flying` BOOL,
  `aircraft_flight_mode` VARCHAR(30),
  `aircraft_flight_mode_value` INT(12),
  `aircraft_imu_preheating` BOOL,
  `aircraft_ultrasonic_on` BOOL,
  `aircraft_ultrasonic_altitude` DOUBLE(12),
  `aircraft_vision_on` BOOL,
  `aircraft_gps_signal` BOOL,
  `aircraft_gps_signal_value` DOUBLE(12),
  `aircraft_smart_gohome_flight_time_remaining` INT(12),
  `aircraft_smart_gohome_requesting` BOOL,
  `aircraft_last_updated` VARCHAR(40),
  `battery_power` INT(12),
  `battery_current` INT(12),
  `battery_voltage` INT(12),
  `battery_temperature` INT(12),
  `battery_charge` INT(12),
  `battery_last_updated` VARCHAR(40),
  `battery_cell_one` INT(12),
  `battery_cell_two` INT(12),
  `battery_cell_three` INT(12),
  `battery_cell_four` INT(12),
  `battery_cell_five` INT(12),
  `battery_cell_six` INT(12),
  `battery_cell_last_updated` VARCHAR(40),
  `gcs_lat` DOUBLE(12),
  `gcs_lon` DOUBLE(12),
  `gcs_location_last_updated` VARCHAR(40),
  `gimbal_pitch` DOUBLE(12),
  `gimbal_roll` DOUBLE(12),
  `gimbal_yaw` DOUBLE(12),
  `gimbal_mode` DOUBLE(12),
  FOREIGN KEY (`logfile_id`) REFERENCES `logfile` (`logfile_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);