CREATE TABLE IF NOT EXISTS `flight_logfile` (
  `logfile_id` INTEGER NOT NULL AUTO_INCREMENT,
  `exchange_type` VARCHAR(80),
  `exchanger` VARCHAR(255),
  `uploadingOrgUuid` VARCHAR(80),
  `uploadingPilotUuid` VARCHAR(80),
  `flight_session_id` VARCHAR(255),
  `file_creation_dtg` VARCHAR(40),
  `file_logging_type` VARCHAR(80),
  `filename` VARCHAR(255),
  `altitude_system` VARCHAR(80),
  `logging_start_dtg` VARCHAR(40),
  `camera_serial_number` VARCHAR(80),
  `camera_model` VARCHAR(80),
  `camera_firmware_version` VARCHAR(80),
  `gimbal_serial_number` VARCHAR(80),
  `gimbal_firmware_version` VARCHAR(80),
  `remote_controller_serial_number` VARCHAR(80),
  `remote_controller_firmware_version` VARCHAR(80),
  `aircraft_manufacturer` VARCHAR(80),
  `aircraft_serial_number` VARCHAR(80),
  `aircraft_name` VARCHAR(255),
  `aircraft_model` VARCHAR(255),
  `aircraft_firmware_version` VARCHAR(80),
  `home_location_lat` VARCHAR(30),
  `home_location_lon` VARCHAR(30),
  `aircraft_smart_gohome_flight_return_time` DECIMAL(30, 18),
  `aircraft_smart_gohome_landing_power` INTEGER,
  `aircraft_smart_gohome_return_power` INTEGER,
  `aircraft_smart_gohome_landing_radius` DECIMAL(30, 18),
  `aircraft_smart_gohome_landing_time` DECIMAL(30, 18),
  `gcs_manufacturer` VARCHAR(80),
  `gcs_model` VARCHAR(80),
  `gcs_version` VARCHAR(80),
  `flight_session_start` VARCHAR(40),
  `flight_session_end` VARCHAR(40),
  `flight_controller_serial_number` VARCHAR(80),
  `flight_controller_firmware_version` VARCHAR(80),
  `battery_serial_number` VARCHAR(80),
  `battery_remaining_life` VARCHAR(80),
  `battery_discharges` VARCHAR(20),
  `battery_full_charge_volume` VARCHAR(20),
  `battery_cell_number` VARCHAR(20),
  `battery_firmware_version` VARCHAR(80),
  `device_origin_user_interface_idiom` VARCHAR(80),
  `device_origin_operating_system` VARCHAR(80),
  `device_origin_model` VARCHAR(80),
  `device_origin_device_ssid` VARCHAR(80),
  `message_type` VARCHAR(80),
  PRIMARY KEY (`logfile_id`)
);